spring.application.name=horse-racing-tournament

# Cấu hình kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HorseRacingDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Server port
server.port=8080 spring.application.name=horse-racing-tournament